force-app/main/default/objects/Item__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
                <default>true</default>
                <label>Electronics</label>
            </value>
            <value>
                <fullName>Clothes</fullName>
            </value>
            <value>
                <fullName>Books</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Clothes</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client_ID</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchases</relationshipLabel>
    <relationshipName>Purchases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseLine__c/fields/Purchase_Id__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Id__c</fullName>
    <label>Purchase_Id</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>PurchaseLines</relationshipLabel>
    <relationshipName>PurchaseLines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ItemController.cls
public with sharing class ItemController {

    // get goods
    @AuraEnabled(cacheable=true)
    public static List<Item__c> getAllItems() {
        return [
            SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
            FROM Item__c
            ORDER BY Name
        ];
    }

    // get goods by type and family
    @AuraEnabled(cacheable=true)
    public static List<Item__c> getItemsByFilter(String familyValue, String typeValue) {
        return [
            SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
            FROM Item__c
            WHERE Family__c = :familyValue AND Type__c = :typeValue
            ORDER BY Name
        ];
    }

    // search by name and description
    @AuraEnabled(cacheable=true)
    public static List<Item__c> searchItems(String searchKey) {
        String likeExp = '%' + searchKey + '%';
        return [
            SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
            FROM Item__c
            WHERE Name LIKE :likeExp OR Description__c LIKE :likeExp
            ORDER BY Name
        ];
    }

    // search for details
    @AuraEnabled(cacheable=true)
    public static Item__c getItemDetails(Id itemId) {
        return [
            SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
            FROM Item__c
            WHERE Id = :itemId
            LIMIT 1
        ];
    }

    // create purchase and lines
    @AuraEnabled
    public static Id checkoutCart(Id accountId, List<PurchaseLine__c> cartLines) {
    
        Purchase__c purchase = new Purchase__c();
        purchase.Client_ID__c = accountId;
        purchase.TotalItems__c = 0;   // will be changed by the trigger
        purchase.GrandTotal__c = 0;   // 
        insert purchase;

        
        for (PurchaseLine__c line : cartLines) {
            line.Purchase_Id__c = purchase.Id;
        }
        insert cartLines;

        return purchase.Id;
    }

    @AuraEnabled(cacheable=true)
    public static List<Item__c> getItems() {
        return [
            SELECT Id, Name, Description__c, Family__c, Type__c, Image__c, Price__c
            FROM Item__c
            ORDER BY Name
        ];
    }
}